--
-- PostgreSQL database dump
--

-- Dumped from database version 12.16
-- Dumped by pg_dump version 17.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: quests; Type: TABLE; Schema: public; Owner: tsdbadmin
--

CREATE TABLE public.quests (
    "seasonNumber" numeric(78,0) NOT NULL,
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    "previousQuestId" uuid,
    count numeric(78,0) NOT NULL,
    prime boolean DEFAULT false NOT NULL,
    steps jsonb DEFAULT '[]'::jsonb NOT NULL,
    "loyaltyPoints" numeric(78,0) DEFAULT '0'::numeric NOT NULL,
    boost numeric(78,0) DEFAULT '0'::numeric NOT NULL,
    "boostLimit" numeric(78,0),
    "limit" numeric(78,0) DEFAULT '1'::numeric NOT NULL,
    period public.quest_period NOT NULL,
    rank public.loyalty_rank DEFAULT 'BRONZE_5'::public.loyalty_rank NOT NULL,
    "questType" public.quest_type NOT NULL,
    featured boolean DEFAULT false NOT NULL,
    "tweetId" text,
    "tweetAction" public.tweet_action,
    "order" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.quests OWNER TO tsdbadmin;

--
-- Data for Name: quests; Type: TABLE DATA; Schema: public; Owner: tsdbadmin
--

COPY public.quests ("seasonNumber", id, name, "previousQuestId", count, prime, steps, "loyaltyPoints", boost, "boostLimit", "limit", period, rank, "questType", featured, "tweetId", "tweetAction", "order") FROM stdin;
1	695e95db-fd83-429d-a986-a7e0dd1ebefc	Buy an NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	15	0	\N	10	DAILY	BRONZE_5	DAILY	f	\N	\N	0
1	41d01ab5-7e0b-4850-b62e-5e84d9cced4e	Buy your first NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	100	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	\N	\N	0
1	c67b3a44-3e6c-4657-989e-93f73380d66b	Buy 5 NFTs	\N	5	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	10	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	2ac1f9de-7d1e-44e5-a2b9-a0a52b34108d	Sell an NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	15	0	\N	10	DAILY	BRONZE_5	DAILY	f	\N	\N	0
1	ce03b6a0-d1a6-4203-ac1e-5f1082f5e92a	Sell your first NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	100	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	\N	\N	0
1	1548eaa3-7828-4237-8e9d-2c95fc5b8d57	Sell 5 NFTs	\N	5	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	10	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	8a78aa1d-b1ea-408d-84dd-214189a5738d	List your first NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "order.user"}, {"delta": null, "value": "\\"ASK\\"", "operator": "EQ", "property": "order.type"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.isSpaaceMarketplace"}], "trigger": "ORDER"}]	100	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	\N	\N	0
1	800cb2e6-f74d-4000-921f-e4e978000d63	Add your username	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "user.address"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "user.name"}], "trigger": "USER"}]	150	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	\N	\N	0
1	291e86f2-ebc4-4a3c-8d29-f06d0af95e5e	Add your email	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "user.address"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "user.email"}], "trigger": "USER"}]	150	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	\N	\N	0
1	f97ebd38-7fde-4571-81fe-b04b91d8d683	Buy 100 NFTs	4501f28f-b970-4f58-850a-37e562f28ae5	100	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	250	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	eff279e0-c288-4dec-9328-852a6ed16efd	List NFTs	\N	1	t	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "order.user"}, {"delta": null, "value": "\\"ASK\\"", "operator": "EQ", "property": "order.type"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.isSpaaceMarketplace"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.collection.prime"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.passesFloorCheck"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.active"}], "trigger": "ORDER"}]	0	0	\N	1	SEASONAL	BRONZE_5	PRIME	f	\N	\N	0
1	3e9eca0b-c482-4d82-870a-1e070c5f844d	Buy 10 NFTs	c67b3a44-3e6c-4657-989e-93f73380d66b	10	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	25	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	62012472-b821-4ca6-b0a8-3c79dbd3f726	Buy 25 NFTs	3e9eca0b-c482-4d82-870a-1e070c5f844d	25	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	50	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	4501f28f-b970-4f58-850a-37e562f28ae5	Buy 50 NFTs	62012472-b821-4ca6-b0a8-3c79dbd3f726	50	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	150	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	dc001cb3-021e-4d8d-8aa3-b44f3ec87590	Place Collection Bids	\N	1	t	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "order.user"}, {"delta": null, "value": "\\"BID\\"", "operator": "EQ", "property": "order.type"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.isSpaaceMarketplace"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.collection.prime"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.floorPricePresent"}, {"delta": "-86400000", "value": "now", "operator": "LTE", "property": "order.timestamp"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.active"}, {"delta": null, "value": "null", "operator": "EQ", "property": "order.tokenId"}], "trigger": "ORDER"}]	0	0	\N	1	SEASONAL	BRONZE_5	PRIME	f	\N	\N	0
1	56f506fa-5d3f-41ae-a42c-990b5d34b462	Buy 250 NFTs	f97ebd38-7fde-4571-81fe-b04b91d8d683	250	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	500	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	37b7ad1c-9604-484c-8067-4605fbe81a23	Buy 500 NFTs	56f506fa-5d3f-41ae-a42c-990b5d34b462	500	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	1500	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	87bc2d53-3a26-42d6-80c6-e714c4a79601	Buy 1,000 NFTs	37b7ad1c-9604-484c-8067-4605fbe81a23	1000	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	2500	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	2d774a0c-197f-4f1b-acd0-8bd2c5a23f0d	Sell 10 NFTs	1548eaa3-7828-4237-8e9d-2c95fc5b8d57	10	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	25	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	58cf4d38-cee2-4303-ae68-636fb74918d5	Sell 25 NFTs	2d774a0c-197f-4f1b-acd0-8bd2c5a23f0d	25	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	50	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	26310dbc-7904-408c-8f38-a2a7369979db	Sell 50 NFTs	58cf4d38-cee2-4303-ae68-636fb74918d5	50	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	150	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	ca1d8da1-968a-4044-874c-9c09a946b2d5	Sell 100 NFTs	26310dbc-7904-408c-8f38-a2a7369979db	100	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	250	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	42783597-08f9-4eb5-859b-2ac1ce1173e7	Sell 250 NFTs	ca1d8da1-968a-4044-874c-9c09a946b2d5	250	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	500	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	77f63cff-761b-4fb2-a9f4-98473a0b7b80	Sell 500 NFTs	42783597-08f9-4eb5-859b-2ac1ce1173e7	500	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	1500	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	6011b1e4-10bd-443d-a029-6657b1c84b25	Sell 1,000 NFTs	77f63cff-761b-4fb2-a9f4-98473a0b7b80	1000	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}], "trigger": "SALE"}]	2500	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	\N	\N	0
1	be97b56d-e61b-4e39-a91e-2438ff52abd7	List a Prime NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "order.user"}, {"delta": null, "value": "\\"ASK\\"", "operator": "EQ", "property": "order.type"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.isSpaaceMarketplace"}, {"delta": null, "value": "true", "operator": "EQ", "property": "order.collection.prime"}], "trigger": "ORDER"}]	50	0	\N	10	DAILY	BRONZE_5	DAILY	f	\N	\N	0
1	01627a24-9394-4cf1-85bf-c90f4d0493c8	Buy a Prime NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.to"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.from"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.collection.prime"}], "trigger": "SALE"}]	100	0	\N	10	DAILY	BRONZE_5	DAILY	f	\N	\N	0
1	b190d64a-92f2-48dd-a976-c7fdf5253a69	Sell a Prime NFT	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "sale.from"}, {"delta": null, "value": "user", "operator": "NEQ", "property": "sale.to"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.isSpaaceMarketplace"}, {"delta": null, "value": "100", "operator": "GTE", "property": "sale.usdPrice"}, {"delta": null, "value": "true", "operator": "EQ", "property": "sale.collection.prime"}], "trigger": "SALE"}]	100	0	\N	10	DAILY	BRONZE_5	DAILY	f	\N	\N	0
1	7f5af1d4-a649-4854-87ca-a9133c0f27ae	Like Spaace’s latest post on X for the first time	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	1902656010495348969	LIKE	0
1	3d8eb5f2-4822-4644-85fd-9d41280ee30f	Repost Spaace’s latest post on X for the first time	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	1902656010495348969	REPOST	0
1	faed510e-fb2e-450f-a965-05b8e5a61699	Reply to Spaace’s latest post on X for the first time	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	SEASONAL	BRONZE_5	GENESIS	f	1902656010495348969	REPLY	0
1	240b0e1a-8f10-442f-aae4-04497a9e27b8	Like Spaace’s latest post on X	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	DAILY	BRONZE_5	DAILY	f	1902656010495348969	LIKE	0
1	f685de62-4052-4a80-bc8d-0dc9c2f8a838	Repost Spaace’s latest post on X	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	DAILY	BRONZE_5	DAILY	f	1902656010495348969	REPOST	0
1	df7a1063-5b80-45bf-97b0-d7148905f0f4	Reply to Spaace’s latest post on X	\N	1	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	DAILY	BRONZE_5	DAILY	f	1902656010495348969	REPLY	0
1	caa9b9a1-b83c-40cd-83d2-b54bebf958fe	Like 5 of Spaace’s latest post on X	\N	5	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	10	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	LIKE	0
1	22c6d1e2-4a3a-4704-9475-f6ed0c20d3d6	Repost 5 of Spaace’s latest post on X	\N	5	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	10	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPOST	0
1	dc3e7f49-f2a2-4735-9b78-5f678aa17dc9	Reply to 5 Spaace’s latest post on X	\N	5	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	10	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPLY	0
1	8cb4d890-2404-4f6c-b718-12fd83305e4d	Like 10 of Spaace’s latest post on X	caa9b9a1-b83c-40cd-83d2-b54bebf958fe	10	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	25	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	LIKE	0
1	fa4a8b9d-92b2-4d9a-a451-30d2efe4e3d3	Like 25 of Spaace’s latest post on X	8cb4d890-2404-4f6c-b718-12fd83305e4d	25	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	50	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	LIKE	0
1	3e2094a0-91c2-478b-92fc-dc46ce350786	Like 50 of Spaace’s latest post on X	fa4a8b9d-92b2-4d9a-a451-30d2efe4e3d3	50	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	LIKE	0
1	de6aefbf-3dec-4f29-9f11-35bbf1622aa2	Like 75 of Spaace’s latest post on X	3e2094a0-91c2-478b-92fc-dc46ce350786	75	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	150	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	LIKE	0
1	74704518-7695-4c63-9710-aee958fce5cd	Like 100 of Spaace’s latest post on X	de6aefbf-3dec-4f29-9f11-35bbf1622aa2	100	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	250	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	LIKE	0
1	e3e6448f-4c6c-477e-8730-253e54716d52	Like 150 of Spaace’s latest post on X	74704518-7695-4c63-9710-aee958fce5cd	150	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"LIKE\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	400	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	LIKE	0
1	823a8caa-bc46-4610-ab21-0a1d77429e21	Repost 10 of Spaace’s latest post on X	22c6d1e2-4a3a-4704-9475-f6ed0c20d3d6	10	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	25	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPOST	0
1	3738ad77-3f1c-4691-8d76-20aa38865f42	Repost 25 of Spaace’s latest post on X	823a8caa-bc46-4610-ab21-0a1d77429e21	25	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	50	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPOST	0
1	cceb60b7-0ddc-4fdd-ab8e-1a4af8daa3ec	Repost 50 of Spaace’s latest post on X	3738ad77-3f1c-4691-8d76-20aa38865f42	50	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPOST	0
1	c227229e-e09d-44fa-a2ef-f6930999ccc3	Repost 75 of Spaace’s latest post on X	cceb60b7-0ddc-4fdd-ab8e-1a4af8daa3ec	75	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	150	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPOST	0
1	9088b4be-cb7e-40b0-aceb-b491c5bd4cde	Repost 100 of Spaace’s latest post on X	c227229e-e09d-44fa-a2ef-f6930999ccc3	100	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	250	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPOST	0
1	ab828c96-b974-4e3a-a1af-a2a6274d12b1	Repost 150 of Spaace’s latest post on X	9088b4be-cb7e-40b0-aceb-b491c5bd4cde	150	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPOST\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	400	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPOST	0
1	7d826834-aa0e-4020-8e5c-caaa4807c489	Reply to 10 Spaace’s latest post on X	dc3e7f49-f2a2-4735-9b78-5f678aa17dc9	10	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	25	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPLY	0
1	3681a197-af89-40ce-9891-8118d2bd00c0	Reply to 25 Spaace’s latest post on X	7d826834-aa0e-4020-8e5c-caaa4807c489	25	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	50	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPLY	0
1	5266dc81-a986-4187-959d-51d61977b016	Reply to 50 Spaace’s latest post on X	3681a197-af89-40ce-9891-8118d2bd00c0	50	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	100	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPLY	0
1	051b1aac-5d49-48e3-b429-e68fe130bccd	Reply to 75 Spaace’s latest post on X	5266dc81-a986-4187-959d-51d61977b016	75	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	150	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPLY	0
1	d30bc87e-ae3c-49e7-a12f-bc4e6d50f3aa	Reply to 100 Spaace’s latest post on X	051b1aac-5d49-48e3-b429-e68fe130bccd	100	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	250	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPLY	0
1	d566bc3f-dc48-4c29-9c85-7c3ace8e71bd	Reply to 150 Spaace’s latest post on X	d30bc87e-ae3c-49e7-a12f-bc4e6d50f3aa	150	f	[{"cron": false, "rules": [{"delta": null, "value": "user", "operator": "EQ", "property": "interaction.user"}, {"delta": null, "value": "\\"TWEET_ACTION\\"", "operator": "EQ", "property": "interaction.type"}, {"delta": null, "value": "\\"REPLY\\"", "operator": "EQ", "property": "interaction.actionType"}, {"delta": null, "value": "null", "operator": "NEQ", "property": "interaction.tweetId"}], "trigger": "USER_INTERACTION"}]	400	0	\N	1	SEASONAL	BRONZE_5	PROGRESSIVE	f	1902656010495348969	REPLY	0
\.


--
-- Name: quests PK_3a6a6a0b62780e61b384452424b; Type: CONSTRAINT; Schema: public; Owner: tsdbadmin
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT "PK_3a6a6a0b62780e61b384452424b" PRIMARY KEY ("seasonNumber", id);


--
-- Name: quests REL_f94aec94cffab50834b8edaa1f; Type: CONSTRAINT; Schema: public; Owner: tsdbadmin
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT "REL_f94aec94cffab50834b8edaa1f" UNIQUE ("seasonNumber", "previousQuestId");


--
-- Name: quests UQ_4d91b52a8e3fe3ce2caac4a6139; Type: CONSTRAINT; Schema: public; Owner: tsdbadmin
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT "UQ_4d91b52a8e3fe3ce2caac4a6139" UNIQUE ("seasonNumber", name);


--
-- Name: quests FK_0d6ae099c6fe57b0aaf4a8ed5b2; Type: FK CONSTRAINT; Schema: public; Owner: tsdbadmin
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT "FK_0d6ae099c6fe57b0aaf4a8ed5b2" FOREIGN KEY ("seasonNumber") REFERENCES public.seasons(number);


--
-- Name: quests FK_f94aec94cffab50834b8edaa1fe; Type: FK CONSTRAINT; Schema: public; Owner: tsdbadmin
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT "FK_f94aec94cffab50834b8edaa1fe" FOREIGN KEY ("seasonNumber", "previousQuestId") REFERENCES public.quests("seasonNumber", id);


--
-- PostgreSQL database dump complete
--

